export const data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
      genre_ids: [28, 27, 53],
      id: 1096197,
      original_language: "en",
      original_title: "No Way Up",
      overview:
        "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
      popularity: 2288.6,
      poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
      release_date: "2024-01-18",
      title: "No Way Up",
      video: false,
      vote_average: 6.358,
      vote_count: 402,
    },
    {
      adult: false,
      backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
      genre_ids: [28, 878, 12, 14],
      id: 823464,
      original_language: "en",
      original_title: "Godzilla x Kong: The New Empire",
      overview:
        "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
      popularity: 1883.28,
      poster_path: "/gmGK5Gw5CIGMPhOmTO0bNA9Q66c.jpg",
      release_date: "2024-03-27",
      title: "Godzilla x Kong: The New Empire",
      video: false,
      vote_average: 6.65,
      vote_count: 719,
    },
    {
      adult: false,
      backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
      genre_ids: [16, 28, 10751, 35, 14],
      id: 1011985,
      original_language: "en",
      original_title: "Kung Fu Panda 4",
      overview:
        "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
      popularity: 1665.369,
      poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
      release_date: "2024-03-02",
      title: "Kung Fu Panda 4",
      video: false,
      vote_average: 7.154,
      vote_count: 1237,
    },
    {
      adult: false,
      backdrop_path: "/8uVKfOJUhmybNsVh089EqLHUYEG.jpg",
      genre_ids: [878, 12],
      id: 693134,
      original_language: "en",
      original_title: "Dune: Part Two",
      overview:
        "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
      popularity: 1618.076,
      poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      release_date: "2024-02-27",
      title: "Dune: Part Two",
      video: false,
      vote_average: 8.273,
      vote_count: 3283,
    },
    {
      adult: false,
      backdrop_path: "/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg",
      genre_ids: [878, 28, 18, 10770],
      id: 934632,
      original_language: "en",
      original_title: "Rebel Moon - Part Two: The Scargiver",
      overview:
        "The rebels gear up for battle against the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
      popularity: 1125.677,
      poster_path: "/aqKtSJdsUYNhEYfV42AYpamhEle.jpg",
      release_date: "2024-04-19",
      title: "Rebel Moon - Part Two: The Scargiver",
      video: false,
      vote_average: 6.241,
      vote_count: 372,
    },
    {
      adult: false,
      backdrop_path: "/qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg",
      genre_ids: [12, 28, 18],
      id: 845111,
      original_language: "fr",
      original_title: "Les trois mousquetaires : Milady",
      overview:
        "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
      popularity: 1071.691,
      poster_path: "/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg",
      release_date: "2023-12-13",
      title: "The Three Musketeers: Milady",
      video: false,
      vote_average: 6.588,
      vote_count: 313,
    },
    {
      adult: false,
      backdrop_path: "/pIFGZRCWjdQwECoXcphCCe1tl0B.jpg",
      genre_ids: [27, 9648, 53],
      id: 1041613,
      original_language: "en",
      original_title: "Immaculate",
      overview:
        "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
      popularity: 987.417,
      poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
      release_date: "2024-03-20",
      title: "Immaculate",
      video: false,
      vote_average: 6.34,
      vote_count: 231,
    },
    {
      adult: false,
      backdrop_path: "/fUC5VsQcU3m6zmYMD96R7RqPuMn.jpg",
      genre_ids: [28, 80, 53],
      id: 1105407,
      original_language: "en",
      original_title: "Damaged",
      overview:
        "A Chicago detective travels to Scotland after an emerging serial killer’s crimes match those that he investigated five years earlier, one of which was the crime scene of his murdered girlfriend.",
      popularity: 945.813,
      poster_path: "/tMO0YLXgJZBnIAjoTSz26zE33YN.jpg",
      release_date: "2024-04-12",
      title: "Damaged",
      video: false,
      vote_average: 5.6,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg",
      genre_ids: [28, 53],
      id: 359410,
      original_language: "en",
      original_title: "Road House",
      overview:
        "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
      popularity: 726.461,
      poster_path: "/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
      release_date: "2024-03-08",
      title: "Road House",
      video: false,
      vote_average: 7.048,
      vote_count: 1539,
    },
    {
      adult: false,
      backdrop_path: "/unCdljyU2FuUBDUcdZezeI9yaaj.jpg",
      genre_ids: [878, 9648, 53, 28],
      id: 720321,
      original_language: "en",
      original_title: "Breathe",
      overview:
        "Air-supply is scarce in the near future, forcing a mother and daughter to fight for survival when two strangers arrive desperate for an oxygenated haven.",
      popularity: 716.164,
      poster_path: "/wTW2t8ocWDlHns8I7vQxuqkyK58.jpg",
      release_date: "2024-04-04",
      title: "Breathe",
      video: false,
      vote_average: 5.5,
      vote_count: 50,
    },
    {
      adult: false,
      backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 707.031,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-06",
      title: "Migration",
      video: false,
      vote_average: 7.549,
      vote_count: 1223,
    },
    {
      adult: false,
      backdrop_path: "/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg",
      genre_ids: [878, 28, 14, 12],
      id: 601796,
      original_language: "ko",
      original_title: "외계+인 1부",
      overview:
        "Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.",
      popularity: 704.761,
      poster_path: "/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg",
      release_date: "2022-07-20",
      title: "Alienoid",
      video: false,
      vote_average: 6.915,
      vote_count: 281,
    },
    {
      adult: false,
      backdrop_path: "/keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg",
      genre_ids: [28, 53, 10752],
      id: 784651,
      original_language: "hi",
      original_title: "फाइटर",
      overview:
        "Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.",
      popularity: 684.849,
      poster_path: "/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg",
      release_date: "2024-01-24",
      title: "Fighter",
      video: false,
      vote_average: 5.487,
      vote_count: 39,
    },
    {
      adult: false,
      backdrop_path: "/cIztAxDn3H8JylRaJwiHHpkGe53.jpg",
      genre_ids: [10751, 35, 16],
      id: 1239146,
      original_language: "en",
      original_title: "Woody Woodpecker Goes to Camp",
      overview:
        "After getting kicked out of the forest, Woody thinks he's found a forever home at Camp Woo Hoo — until an inspector threatens to shut down the camp.",
      popularity: 665.37,
      poster_path: "/mMnzNYvpqLLLdgF5TMmXfuy6wzx.jpg",
      release_date: "2024-04-12",
      title: "Woody Woodpecker Goes to Camp",
      video: false,
      vote_average: 6.986,
      vote_count: 72,
    },
    {
      adult: false,
      backdrop_path: "/dcnSWFCtk4b2aIzkhq6IDbzoIf1.jpg",
      genre_ids: [28, 35],
      id: 942047,
      original_language: "en",
      original_title: "Outsource",
      overview:
        "A police chief hires an old friend, who is an international spy, to help him search for a wanted suspect in the Philippines. When the chief dies, all evidence points towards the spy, and he must go to extremes to defend himself.",
      popularity: 643.167,
      poster_path: "/zIAF0UXtCJTJOYNYWiBfyifaaOi.jpg",
      release_date: "2022-01-18",
      title: "Outsource",
      video: false,
      vote_average: 3.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
      genre_ids: [28, 14],
      id: 634492,
      original_language: "en",
      original_title: "Madame Web",
      overview:
        "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
      popularity: 637.433,
      poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
      release_date: "2024-02-14",
      title: "Madame Web",
      video: false,
      vote_average: 5.624,
      vote_count: 1126,
    },
    {
      adult: false,
      backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: "en",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
      popularity: 596.331,
      poster_path: "/r7Ymod44pKV2lsLzniF4GxTg3X8.jpg",
      release_date: "2024-05-08",
      title: "Kingdom of the Planet of the Apes",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/lP0G6f00CjOKdRECyGrT0kaMSrL.jpg",
      genre_ids: [18],
      id: 383634,
      original_language: "ja",
      original_title: "肉体の門",
      overview:
        "Prostitutes in burnt out Tokyo ghetto of post-WWII Japan peddle their flesh and save one-third of their money for a proposed dancehall to be named Paradise. The hookers live in a bombed-out building, but they accept the precarious situation with typical resolve.",
      popularity: 593.877,
      poster_path: "/raNbLci95MJ3L3dMnG7L7bD37lY.jpg",
      release_date: "1988-04-09",
      title: "Carmen 1945",
      video: false,
      vote_average: 4,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg",
      genre_ids: [14, 12, 35],
      id: 967847,
      original_language: "en",
      original_title: "Ghostbusters: Frozen Empire",
      overview:
        "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
      popularity: 580.602,
      poster_path: "/6faYaQyiBPhqAizldJKq21mIVaE.jpg",
      release_date: "2024-03-20",
      title: "Ghostbusters: Frozen Empire",
      video: false,
      vote_average: 6.495,
      vote_count: 315,
    },
    {
      adult: false,
      backdrop_path: "/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg",
      genre_ids: [28, 53],
      id: 984324,
      original_language: "fr",
      original_title: "Le salaire de la peur",
      overview:
        "When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.",
      popularity: 545.125,
      poster_path: "/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg",
      release_date: "2024-03-28",
      title: "The Wages of Fear",
      video: false,
      vote_average: 5.796,
      vote_count: 181,
    },
  ],
  total_pages: 43742,
  total_results: 874827,
};
